#!/usr/bin/env python3
"""Generate reference-check.md for issue #124 -- the citation-authenticity report.

It is generated FROM the built manuscript and the verified pool, never assembled by hand, so a
citation that no sentence uses cannot appear and a cited key cannot be missing a verdict.

Each entry records: the citation key -> the verification method -> the result -> the live record
that was read.  A resolved identifier is NOT accepted as proof: a remembered identifier can resolve
to a different real paper, so the check is a TITLE comparison against the live record, and the
pool's `title_match` is that comparison's score (two-sided).
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "reference-check.md")
MAN = os.path.join(HERE, "manuscript.md")
# The pool is read from the COMMITTED reference layer (refs/pool.json), not from the git-ignored
# research/ workspace: a committed generator that reads a directory the repository does not carry
# works on the authoring machine and fails on a fresh checkout, so the one-command reproduction
# would not reproduce.  refs/pool.json is the pool the manuscript was built and verified against.
POOL = os.path.join(HERE, "refs", "pool.json")
MIN_REFS = 100
THRESHOLD = 0.80


def main():
    pool = json.load(open(POOL))
    text = open(MAN).read()
    refs = text.split("## References", 1)[1]
    rows = []
    for m in re.finditer(r"^(\d+)\.\s+(.*)$", refs, re.M):
        n = int(m.group(1))
        line = m.group(2)
        ident = re.search(r"arXiv:([0-9]{4}\.[0-9]{4,5}(?:v[0-9]+)?)", line)
        if ident:
            key = ident.group(1).split("v")[0]
        else:
            doi = re.search(r"\b(10\.[0-9]{4,9}/\S+?)(?=\s|$)", line)
            if not doi:
                raise SystemExit("reference %d carries no identifier -- refusing to report it" % n)
            key = doi.group(1).rstrip(".")
        if key not in pool:
            raise SystemExit("reference %d (%s) is not in the verified pool" % (n, key))
        rows.append((n, key, pool[key]))

    if len(rows) < MIN_REFS:
        raise SystemExit("the manuscript cites %d references; the bar is %d" % (len(rows), MIN_REFS))

    ver = {r["key"]: r for r in json.load(open(os.path.join(HERE, "citation-verification.json")))}
    missing = [k for _n, k, _v in rows if k not in ver]
    if missing:
        raise SystemExit("%d cited reference(s) carry no live verification result: %s"
                         % (len(missing), missing[:5]))
    bad = [(k, ver[k]["verdict"]) for _n, k, _v in rows if ver[k]["verdict"] != "VERIFIED"]
    if bad:
        raise SystemExit("refusing to report a pass: %s" % bad[:5])
    worst = min(ver[k]["title_match"] for _n, k, _v in rows)
    by_source = {}
    for _n, _k, v in rows:
        by_source[v["source"]] = by_source.get(v["source"], 0) + 1

    L = []
    L.append("# Reference authenticity check -- issue #124")
    L.append("")
    L.append("Every cited reference was checked against a LIVE external record by")
    L.append("`verify_citations.py`; the results are in `citation-verification.json` and the table")
    L.append("below is rendered from them.  A resolver that merely answers is not enough: a")
    L.append("remembered identifier can resolve to a DIFFERENT real paper, so the check is the")
    L.append("returned TITLE against the stored title (two-sided token match, threshold %.2f)." % THRESHOLD)
    L.append("No identifier here was typed from memory into the manuscript; each came from the")
    L.append("verified pool.")
    L.append("")
    L.append("- manuscript: `manuscript.md` (generated by `build_manuscript.py` from the source parts)")
    L.append("- cited references: **%d** (journal bar %d)" % (len(rows), MIN_REFS))
    L.append("- by source: %s" % ", ".join("%s %d" % (k, v) for k, v in sorted(by_source.items())))
    L.append("- every cited entry was matched against its LIVE record at a two-sided title score")
    L.append("  >= %.2f; the worst observed score is **%.3f**" % (THRESHOLD, worst))
    L.append("- carrier, arXiv: the **abstract page** `citation_title` meta tag -- chosen because the")
    L.append("  `id_list` API was throttled (HTTP 429) during this pass, and the page carries the same")
    L.append("  field.  The endpoint actually used is recorded per entry in the table.")
    L.append("- carrier, DOI: Crossref `works/<doi>`")
    L.append("")
    L.append("| # | key | method | result | live record read |")
    L.append("|---|-----|--------|--------|------------------|")
    for n, key, v in rows:
        r = ver[key]
        L.append("| %d | `%s` | %s | VERIFIED (%.2f) | %s |"
                 % (n, key, r["method"], r["title_match"], r["live_title"].replace("|", "/")))
    L.append("")
    L.append("A key that cannot be verified is deleted from the manuscript, not reported: the build")
    L.append("refuses to render a citation whose key is absent from the verified pool.")
    open(OUT, "w").write("\n".join(L) + "\n")
    print("wrote %s" % os.path.relpath(OUT, HERE))
    print("  cited %d (bar %d) | worst title match %.2f | sources %s"
          % (len(rows), MIN_REFS, worst, by_source))


if __name__ == "__main__":
    main()
