#!/usr/bin/env python3
"""Issue #50 -- the four figures, written as SVG by this file and by nothing else.

    python3 figures/make_figures_v1.py            # write figures/*.svg from the artefacts
    python3 figures/make_figures_v1.py --check    # regenerate and compare byte for byte
    python3 figures/make_figures_v1.py --facts    # print every value the four figures draw
    python3 figures/make_figures_v1.py --selftest # liveness: one planted change per figure must show

WHY THE FIGURES ARE WRITTEN HERE INSTEAD OF PLOTTED.  Section 3 of the manuscript claims the instrument
is deterministic and its evidence needs a Python interpreter and nothing else.  A figure drawn through
a plotting library would make that claim false for a reader who has to install one, and it would make
the figure's own bytes a function of a library version -- so `--check` could no longer compare them the
way it compares every other artefact.  Writing the SVG here keeps all four figures on the same footing
as the JSON: bytes a rerun must reproduce exactly.

WHAT EACH FIGURE IS, AND WHO OWNS EVERY COORDINATE IT DRAWS:

  fig1_boundary.svg    mean per-step benefit against measured contention, one series per pool size at
                       h = 1.0, with each family's located crossing marked.
                       owner: artefacts/boundary_v2_h100.json -- section 4's boundary.
  fig3_prediction.svg  F, and the blind arm's share 1 - F, against the speculation width h, at the pool
                       sizes that differ.  owner: artefacts/variant_v1.json -- section 4's
                       matched-parallelism control and section 8's answer to "worse than nothing".
  fig2_tail.svg        the registered P2 claim, refuted: mean-matched heavy and light classes, their
                       located boundaries with intervals, and the paired difference per family.
                       owner: artefacts/tail_v1_h100.json.
  fig4_mixture.svg     the step-level reading at the boundary cells: the share of steps whose benefit is
                       negative, with its interval.  owner: artefacts/sideeffect_v1.json.

No number is typed into a figure: every coordinate comes out of the artefact named above, read by the
one `read_artefacts()` that `--facts` and the liveness control also go through.  `--selftest` plants one
change per figure in a throwaway copy of the artefacts and requires the regenerated bytes to differ -- a
figure that would not notice a changed input is a picture of the author's memory rather than a reading.
"""
import copy
import hashlib
import io
import json
import math
import os
import re
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DEFAULT_ARTS = os.path.join(PKG, "artefacts")

W, H = 760, 486
PAD_L, PAD_R, PAD_T, PAD_B = 78, 176, 52, 76   # right pad = legend; bottom = ticks + label + notes

INK = "#1a1a1a"
MUTED = "#555555"
GRID = "#dcdcdc"
RULES = "#c0392b"
SERIES = ["#1f4e79", "#2e7d32", "#b8860b", "#8e44ad", "#0e7490", "#7f8c8d"]

READS = ("boundary_v2_h100.json", "variant_v1.json", "tail_v1_h100.json", "sideeffect_v1.json")


# ------------------------------------------------------------------ the reader every figure goes through
def read_artefacts(dirname=DEFAULT_ARTS):
    """The one reader: the four files the figures draw from, opened by path under `dirname`.

    Returning a mapping rather than letting each figure open its own file is what makes the liveness
    control a control: `--selftest` calls THIS function on a copy of the artefacts with one number
    changed, so the planted value reaches the drawing code exactly as the real one does.
    """
    out = {}
    for name in READS:
        out[name] = json.load(io.open(os.path.join(dirname, name), encoding="utf-8"))
    return out


# ------------------------------------------------------------------------------------ drawing helpers
def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def tick_step(lo, hi, n):
    span = (hi - lo) / float(max(1, n - 1))
    if span <= 0:
        return 1.0
    mag = 10.0 ** math.floor(math.log10(span))
    for mult in (1.0, 2.0, 2.5, 5.0, 10.0):
        if span / (mag * mult) <= 1.35:
            return mag * mult
    return mag * 10.0


def ticks(lo, hi, n=5):
    """Round ticks spanning [lo, hi], derived from the data -- never typed."""
    step = tick_step(lo, hi, n)
    start = math.floor(lo / step) * step
    out = []
    v = start
    while v <= hi + step * 0.4 and len(out) < 14:
        # A tick outside the frame is drawn outside the box: the first version of this function let
        # one through, and figure 1 carried a "-2.00" label under the axis it belonged to.
        if lo <= v <= hi:
            out.append(round(v, 12))
        v += step
    return out


def fmt(v):
    if abs(v) < 1e-12:
        return "0"
    if abs(v) >= 100:
        return "%.0f" % v
    if abs(v) >= 10:
        return "%.1f" % v
    if abs(v) >= 1:
        return "%.2f" % v
    return "%.3f" % v


class Frame(object):
    def __init__(self, x0, x1, y0, y1):
        self.x0, self.x1, self.y0, self.y1 = x0, x1, y0, y1

    def px(self, x):
        return PAD_L + (x - self.x0) / (self.x1 - self.x0) * (W - PAD_L - PAD_R)

    def py(self, y):
        return PAD_T + (1 - (y - self.y0) / (self.y1 - self.y0)) * (H - PAD_T - PAD_B)


def head(title, sub):
    return ['<?xml version="1.0" encoding="UTF-8"?>',
            '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d" '
            'font-family="Helvetica,Arial,sans-serif">' % (W, H, W, H),
            '<rect width="%d" height="%d" fill="#ffffff"/>' % (W, H),
            '<text x="%d" y="24" font-size="14.5" font-weight="bold" fill="%s">%s</text>'
            % (PAD_L - 62, INK, esc(title)),
            '<text x="%d" y="41" font-size="10.5" fill="%s">%s</text>' % (PAD_L - 62, MUTED, esc(sub))]


def frame(fr, xticks, yticks, xlabel, ylabel, xfmt=None, yfmt=None):
    xfmt = xfmt or fmt
    yfmt = yfmt or fmt
    out = []
    for t in yticks:
        yy = fr.py(t)
        out.append('<line x1="%d" y1="%.1f" x2="%d" y2="%.1f" stroke="%s" stroke-width="1"/>'
                   % (PAD_L, yy, W - PAD_R, yy, GRID))
        out.append('<text x="%d" y="%.1f" font-size="9.5" fill="%s" text-anchor="end">%s</text>'
                   % (PAD_L - 6, yy + 3.4, MUTED, esc(yfmt(t))))
    for t in xticks:
        xx = fr.px(t)
        out.append('<line x1="%.1f" y1="%d" x2="%.1f" y2="%d" stroke="%s" stroke-width="1"/>'
                   % (xx, PAD_T, xx, H - PAD_B, GRID))
        out.append('<text x="%.1f" y="%d" font-size="9.5" fill="%s" text-anchor="middle">%s</text>'
                   % (xx, H - PAD_B + 16, MUTED, esc(xfmt(t))))
    out.append('<rect x="%d" y="%d" width="%d" height="%d" fill="none" stroke="%s"/>'
               % (PAD_L, PAD_T, W - PAD_L - PAD_R, H - PAD_T - PAD_B, INK))
    out.append('<text x="%d" y="%d" font-size="11" fill="%s" text-anchor="middle">%s</text>'
               % ((PAD_L + W - PAD_R) // 2, H - 42, INK, esc(xlabel)))
    out.append('<text x="15" y="%d" font-size="11" fill="%s" text-anchor="middle" '
               'transform="rotate(-90 15 %d)">%s</text>'
               % ((PAD_T + H - PAD_B) // 2, INK, (PAD_T + H - PAD_B) // 2, esc(ylabel)))
    return out


def path(pts, fr, colour, width=1.7, dash=None):
    d = " ".join("%s%.2f,%.2f" % ("M" if i == 0 else "L", fr.px(x), fr.py(y))
                 for i, (x, y) in enumerate(pts))
    return '<path d="%s" fill="none" stroke="%s" stroke-width="%.1f"%s/>' % (
        d, colour, width, ' stroke-dasharray="%s"' % dash if dash else '')


def dot(x, y, colour, r=2.4):
    return '<circle cx="%.2f" cy="%.2f" r="%.2f" fill="%s"/>' % (x, y, r, colour)


def legend(x, y, items):
    out = []
    for i, (label, colour, dash) in enumerate(items):
        yy = y + i * 16
        out.append('<line x1="%d" y1="%.1f" x2="%d" y2="%.1f" stroke="%s" stroke-width="2"%s/>'
                   % (x, yy, x + 18, yy, colour, ' stroke-dasharray="%s"' % dash if dash else ''))
        out.append('<text x="%d" y="%.1f" font-size="10" fill="%s">%s</text>'
                   % (x + 23, yy + 3.5, INK, esc(label)))
    return out


NOTES_Y = (H - 24, H - 10)          # the two lines of the strip under the axis label


def strip(lines, colour=None):
    """The figure's own sentences, drawn below the axis label -- one place, never over the data."""
    return [note(PAD_L - 62, NOTES_Y[i], lines[i], colour, 10.0) for i in range(len(lines))]


def note(x, y, text, colour=None, size=9.5):
    return '<text x="%s" y="%.1f" font-size="%.1f" fill="%s">%s</text>' % (
        x, y, size, colour or MUTED, esc(text))


# ------------------------------------------------------------------------------------- the four figures
def fig_boundary(art, facts):
    b = art["boundary_v2_h100.json"]
    rows = [(r["rho_spec"], r["benefit_pct"]) for f in b["families"] for r in f["rows"]]
    x0, x1 = min(x for x, _ in rows) - 0.0015, max(x for x, _ in rows) + 0.0015
    y0, y1 = min(y for _, y in rows) - 1.2, max(y for _, y in rows) + 1.2
    fr = Frame(x0, x1, y0, y1)
    out = head("The speculation boundary: benefit against measured contention",
               "artefacts/boundary_v2_h100.json - h = 1.0, %d seeds per cell, %d pool sizes; each "
               "dashed rule is that family's located crossing"
               % (len(b["seeds"]), len(b["families"])))
    out += frame(fr, ticks(x0, x1, 5), ticks(y0, y1, 5),
                 "measured contention rho of the speculative arm",
                 "mean per-step benefit (% of serial latency)", xfmt=lambda v: "%.3f" % v)
    out.append('<line x1="%d" y1="%.1f" x2="%d" y2="%.1f" stroke="%s" stroke-width="1.4" '
               'stroke-dasharray="6,4"/>' % (PAD_L, fr.py(0.0), W - PAD_R, fr.py(0.0), RULES))
    out.append(note(PAD_L + 4, fr.py(0.0) - 5, "benefit = 0", RULES))
    items = []
    for i, f in enumerate(b["families"]):
        colour = SERIES[i % len(SERIES)]
        pts = sorted((r["rho_spec"], r["benefit_pct"]) for r in f["rows"])
        out.append(path(pts, fr, colour))
        for x, y in pts:
            out.append(dot(fr.px(x), fr.py(y), colour))
        c = f["crossing_rho_spec"]["x_star"]
        out.append('<line x1="%.2f" y1="%d" x2="%.2f" y2="%d" stroke="%s" stroke-width="1.1" '
                   'stroke-dasharray="2,3"/>' % (fr.px(c), PAD_T, fr.px(c), H - PAD_B, colour))
        items.append(("A = %d, crossing %.6f" % (f["agents"], c), colour, None))
        facts["fig1/A=%d/crossing_rho_star" % f["agents"]] = round(c, 10)
        facts["fig1/A=%d/max_benefit_pct" % f["agents"]] = round(max(y for _, y in pts), 6)
    out += legend(W - PAD_R + 8, PAD_T + 14, items)
    out += strip(["the crossing moves from %.6f at A = 16 to %.6f at A = 96 (the artefact's own"
                  % (facts["fig1/A=16/crossing_rho_star"], facts["fig1/A=96/crossing_rho_star"]),
                  "located crossings; the pooled span is %.6f rho)"
                  % (facts["fig1/A=16/crossing_rho_star"] - facts["fig1/A=96/crossing_rho_star"])], INK)
    out.append("</svg>")
    return "\n".join(out) + "\n"


def fig_prediction(art, facts):
    v = art["variant_v1.json"]
    hs = sorted(set(c["h"] for c in v["cells"]))
    pool_of = lambda c: int(re.search(r"/c(\d+)$", c["key"]).group(1))
    # above the agent count the pool number is a coordinate only: c = 4, 8 and 16 draw the same line,
    # and drawing three coincident lines would look like a defect rather than a finding
    shown = [p for p in sorted(set(pool_of(c) for c in v["cells"])) if p <= 4]
    F = dict(((c["h"], pool_of(c)), c["F"]) for c in v["cells"])
    y0 = min(min(F[(h, p)]["ci"][0] for h in hs) for p in shown) - 0.06
    y1 = max(max(1.0 - F[(h, p)]["mean"] for h in hs) for p in shown) + 0.06
    x0, x1 = min(hs) - 0.05, max(hs) + 0.05
    fr = Frame(x0, x1, y0, y1)
    out = head("What a predictor buys, against a blind schedule of the same width",
               "artefacts/variant_v1.json - F = (G_selected - G_blind) / G_selected, %d seeds per "
               "cell, k identical in both arms by construction" % len(v["seeds"]))
    out += frame(fr, hs, ticks(y0, y1, 5),
                 "speculation width h (fraction of steps issued early)",
                 "F, and the blind arm's share 1 - F", xfmt=lambda v: "%.2f" % v)
    out.append('<line x1="%d" y1="%.1f" x2="%d" y2="%.1f" stroke="%s" stroke-width="1.4" '
               'stroke-dasharray="6,4"/>' % (PAD_L, fr.py(0.7), W - PAD_R, fr.py(0.7), RULES))
    out.append(note(PAD_L + 4, fr.py(0.7) - 5, "the registered threshold F = 0.7", RULES))
    items = []
    for j, p in enumerate(shown):
        colour = SERIES[j]
        pts = [(h, F[(h, p)]["mean"]) for h in hs]
        out.append(path(pts, fr, colour, 1.9))
        for h in hs:
            ci = F[(h, p)]["ci"]
            out.append('<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" stroke="%s" stroke-width="1.3"/>'
                       % (fr.px(h), fr.py(ci[0]), fr.px(h), fr.py(ci[1]), colour))
            out.append(dot(fr.px(h), fr.py(F[(h, p)]["mean"]), colour, 2.6))
            facts["fig2/F/pool%d/h%.2f" % (p, h)] = round(F[(h, p)]["mean"], 10)
            facts["fig2/F_ci_hi/pool%d/h%.2f" % (p, h)] = round(ci[1], 10)
        items.append(("F, pool c = %d" % p, colour, None))
    p0 = shown[0]
    out.append(path([(h, 1.0 - F[(h, p0)]["mean"]) for h in hs], fr, MUTED, 1.7, "4,3"))
    for h in hs:
        facts["fig2/blind_share/pool%d/h%.2f" % (p0, h)] = round(1.0 - F[(h, p0)]["mean"], 10)
    items.append(("blind share 1 - F, c = %d" % p0, MUTED, "4,3"))
    out += legend(W - PAD_R + 8, PAD_T + 14, items)
    out += strip(["above the agent count the pool coordinate changes nothing: c = 4, 8 and 16 draw the",
                  "same line, so only 2 and 4 are drawn.  the blind share is 1 - F at c = %d" % p0], INK)
    out.append("</svg>")
    return "\n".join(out) + "\n"


def fig_tail(art, facts):
    t = art["tail_v1_h100.json"]
    fams = sorted(t["p2_first_half"]["per_family"], key=lambda f: f["agents"])
    vals = [f[k]["x_star"] for f in fams for k in ("heavy", "light")]
    fr = Frame(0.0, float(len(fams) * 2 + 1), min(vals) - 0.0015, max(vals) + 0.0015)
    out = head("The registered tail claim, refuted: a heavier tail moves the boundary DOWN",
               "artefacts/tail_v1_h100.json - mean-matched classes, paired by seed, %d seeds, h = 1.0"
               % len(t["seeds"]))
    out += frame(fr, [2 * i + 1 for i in range(len(fams))], ticks(fr.y0, fr.y1, 5),
                 "pool size - each pair is one family, heavy on the left",
                 "located boundary rho* (rho_spec)", xfmt=lambda v: "", yfmt=lambda v: "%.3f" % v)
    items = []
    for i, f in enumerate(fams):
        bx = 2 * i + 1
        for k, (key, colour) in enumerate((("heavy", "#c0392b"), ("light", "#1f4e79"))):
            x = fr.px(bx + (k * 0.5 - 0.25))
            ci = f[key]["ci"]
            out.append('<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" stroke="%s" stroke-width="1.5"/>'
                       % (x, fr.py(ci[0]), x, fr.py(ci[1]), colour))
            out.append(dot(x, fr.py(f[key]["x_star"]), colour, 3.4))
            facts["fig3/A=%d/%s_rho_star" % (f["agents"], key)] = round(f[key]["x_star"], 10)
            facts["fig3/A=%d/%s_ci_lo" % (f["agents"], key)] = round(ci[0], 10)
        facts["fig3/A=%d/paired_delta_mean" % f["agents"]] = round(f["delta"]["mean"], 10)
        out.append('<text x="%.2f" y="%d" font-size="9.5" fill="%s" text-anchor="middle">A = %d</text>'
                   % (fr.px(bx), H - PAD_B + 16, INK, f["agents"]))
        out.append('<text x="%.2f" y="%.1f" font-size="9" fill="%s" text-anchor="middle">'
                   'heavy - light = %.5f</text>' % (fr.px(bx), PAD_T + 16, MUTED, f["delta"]["mean"]))
        if i == 0:
            items = [("heavy tail", "#c0392b", None), ("light tail", "#1f4e79", None)]
    out += legend(W - PAD_R + 8, PAD_T + 14, items)
    out += strip(["the artefact's own verdict: %s" % t["p2_first_half"]["verdict"],
                  "the mean-matched premise holds in %d of the %d pool sizes the artefact reports it for"
                  % (sum(1 for v in t["premise"].values() if v["mean_matched"]), len(t["premise"]))],
                  INK)
    out.append("</svg>")
    return "\n".join(out) + "\n"


def fig_mixture(art, facts):
    s = art["sideeffect_v1.json"]
    cells = [c for m in s["m4b"] for c in m["cells"]]
    lab = lambda c: "A%d/w%d" % (c["agents"], c["workers"])
    fr = Frame(0.0, float(len(cells) * 2 + 1), -0.02, 1.0)
    out = head("At the boundary the mean hides a mixture: about half the steps lose",
               "artefacts/sideeffect_v1.json - the swept cells that straddle each family's crossing "
               "(q = 0); bar = share of steps with negative benefit, rule = the artefact's interval")
    out += frame(fr, [2 * i + 1 for i in range(len(cells))], [0.0, 0.25, 0.5, 0.75, 1.0],
                 "cell (pool size / workers), each read at its family's crossing",
                 "share of steps with negative benefit", xfmt=lambda v: "")
    for i, c in enumerate(cells):
        x = fr.px(2 * i + 1)
        fn, ci = c["frac_negative"], c["frac_negative_ci"]
        out.append('<rect x="%.2f" y="%.2f" width="24" height="%.2f" fill="#1f4e79" opacity="0.85"/>'
                   % (x - 12, fr.py(fn), max(0.0, fr.py(0.0) - fr.py(fn))))
        out.append('<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" stroke="%s" stroke-width="1.7"/>'
                   % (x, fr.py(ci[0]), x, fr.py(ci[1]), RULES))
        out.append('<text x="%.2f" y="%.2f" font-size="9" fill="%s" text-anchor="middle">%.1f%%</text>'
                   % (x, fr.py(fn) - 7, INK, 100.0 * fn))
        out.append('<text x="%.2f" y="%d" font-size="9" fill="%s" text-anchor="middle">%s</text>'
                   % (x, H - PAD_B + 16, INK, esc(lab(c))))
        out.append('<text x="%.2f" y="%.2f" font-size="8.5" fill="#e8eef5" text-anchor="middle">'
                   '%d of %d</text>' % (x, fr.py(fn) + 12, c["n_negative"], c["n_steps"]))
        facts["fig4/%s/frac_negative" % lab(c)] = round(fn, 10)
        facts["fig4/%s/n_negative" % lab(c)] = c["n_negative"]
        facts["fig4/%s/n_steps" % lab(c)] = c["n_steps"]
    out += strip(["the same cells' mean benefit is positive (section 4.6): the average and the per-step",
                  "sign are two readings of the same steps, and the interval rules overlap at the top"], INK)
    out.append("</svg>")
    return "\n".join(out) + "\n"


FIGURES = [("fig1_boundary.svg", fig_boundary),
           ("fig3_prediction.svg", fig_prediction),
           ("fig2_tail.svg", fig_tail),
           ("fig4_mixture.svg", fig_mixture)]

# One planted change per figure, applied to a throwaway copy of the artefacts.  The mutation names the
# number the figure draws -- so a figure whose liveness case does not fire is a figure that is not
# reading that number, whatever its caption says.
MUTATIONS = [
    ("fig1_boundary.svg", "boundary_v2_h100.json", ("families", 0, "rows", 0, "benefit_pct"), 3.0),
    ("fig3_prediction.svg", "variant_v1.json", ("cells", 0, "F", "mean"), 0.11),
    ("fig2_tail.svg", "tail_v1_h100.json", ("p2_first_half", "per_family", 0, "heavy", "x_star"), 0.001),
    ("fig4_mixture.svg", "sideeffect_v1.json", ("m4b", 0, "cells", 0, "frac_negative"), 0.05),
]


def build(name, art):
    fn = dict(FIGURES)[name]
    facts = {}
    return fn(art, facts), facts


def planted(dirname, name, path, delta):
    """A copy of the artefacts with one number moved, by `path` into that file's JSON."""
    tmp = os.path.join(dirname, os.path.basename(name))
    doc = json.load(io.open(os.path.join(DEFAULT_ARTS, name), encoding="utf-8"))
    node = doc
    for key in path[:-1]:
        node = node[key]
    leaf = path[-1]
    was = node[leaf]
    node[leaf] = (was + delta) if isinstance(was, (int, float)) else delta
    io.open(tmp, "w", encoding="utf-8").write(json.dumps(doc, indent=1, sort_keys=True))
    return tmp, was


def selftest():
    """One planted change per figure, plus the base case: the base case must PASS, or the four
    mutations prove nothing about the reader (they would fail for any input)."""
    bad = 0
    art = read_artefacts()
    for name, _ in FIGURES:
        text, _f = build(name, art)
        path = os.path.join(HERE, name)
        have = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
        ok = have == text
        if not ok:
            bad += 1
        print("  base  %-20s %s" % (name, "the committed bytes are what the artefacts say" if ok
                                    else "DIFFERS from the committed figure"))
    tmpdir = tempfile.mkdtemp(prefix="issue50-fig-")
    try:
        for fig, owner, path, delta in MUTATIONS:
            d = os.path.join(tmpdir, fig)
            os.makedirs(d)
            # the mutation goes into a COMPLETE copy of the artefacts -- read_artefacts() opens all
            # four files, and a directory holding only the mutated one would fail for the wrong reason
            for nm in READS:
                if nm != owner:
                    shutil.copyfile(os.path.join(DEFAULT_ARTS, nm), os.path.join(d, nm))
            _tmp, was = planted(d, owner, path, delta)
            mutated = read_artefacts(d)
            text, _f = build(fig, mutated)
            base, _f2 = build(fig, read_artefacts())
            fires = text != base
            print("  plant %-20s %s: %s -> %s ... %s"
                  % (fig, owner, was, was + delta,
                     "the figure moved" if fires else "THE FIGURE DID NOT MOVE (control void)"))
            if not fires:
                bad += 1
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    puts = {"reads": len(READS), "cases": len(MUTATIONS) + len(FIGURES)}
    print("FIGURES SELFTEST: %d case(s), %d not firing" % (puts["cases"], bad))
    return 0 if bad == 0 else 1


def main():
    check = "--check" in sys.argv
    art = read_artefacts()
    bad = 0
    for name, _fn in FIGURES:
        text, facts = build(name, art)
        path = os.path.join(HERE, name)
        if check:
            have = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
            same = have == text
            print("  %-4s %-22s %6d B  sha %s" % ("ok" if same else "DIFF", name, len(text),
                                                 hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]))
            if not same:
                bad += 1
        else:
            io.open(path, "w", encoding="utf-8").write(text)
            print("  wrote %-22s %6d B  %d value(s) drawn" % (name, len(text), len(facts)))
    if check:
        print("FIGURES: %d of %d regenerated byte-identical from the artefacts"
              % (len(FIGURES) - bad, len(FIGURES)))
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    if "--facts" in sys.argv:
        art = read_artefacts()
        allfacts = {}
        for name, _fn in FIGURES:
            _t, f = build(name, art)
            allfacts.update(f)
        print(json.dumps(allfacts, indent=1, sort_keys=True))
        sys.exit(0)
    sys.exit(main())
