#!/usr/bin/env python3
"""Render the generated blocks of reference-check.md for issue #132.

Two blocks are rendered here, both injected between markers and never assembled by hand:

1. **The journal reference gate's output** (the `journal-refgate` block).  The gate
   (`.github/tools/refgate.py`) is editor-side tooling that lives outside this package, so its
   output is carried as the committed receipt `refgate-journal.txt`, produced by the exact command
   in the block's own preamble -- and `reproduce.sh` re-runs the gate and compares against this
   receipt byte-for-byte whenever the journal checkout is present.  A receipt that no command can
   re-derive is a claim about a program (Class 192), so the comparison is the point of the receipt,
   not a decoration on it.

2. **The cited subset**: which of the pool's entries the body actually uses, and confirmation that
   every one came from the verified pool rather than from memory.  Rendered from the built
   `manuscript.md` and `refs/pool.json`, so a citation added to the manuscript without a pool entry
   cannot appear in the report, and the count cannot drift from the body.

`--check` re-renders both into memory and compares against the shipped file, writing nothing.

Run:  python3 make_reference_check.py            (write reference-check.md, staged then os.replace'd)
      python3 make_reference_check.py --check    (verify the committed report is what this renders)
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "reference-check.md")
MAN = os.path.join(HERE, "manuscript.md")
POOL = os.path.join(HERE, "refs", "pool.json")
RECEIPT = os.path.join(HERE, "refgate-journal.txt")
BEGIN = "<!-- cited-subset:begin (generated by make_reference_check.py -- do not edit by hand) -->"
END = "<!-- cited-subset:end -->"
GATE_BEGIN = "<!-- journal-refgate:begin (generated by make_reference_check.py -- do not edit by hand) -->"
GATE_END = "<!-- journal-refgate:end -->"
GATE_CMD = "python3 .github/tools/refgate.py papers/issue-132/manuscript.md"
MIN_REFS = 100


def replace_block(text, begin, end, block):
    """Replace the marked region [begin..end] in `text` with `block`.

    The markers' surrounding newlines belong to the text AROUND the region, not to the block, so
    `block` carries none of them: a block that ends with a newline of its own re-adds one separator
    per run and the rendering stops being idempotent."""
    if begin not in text or end not in text:
        raise SystemExit("the report does not carry the markers %r / %r" % (begin, end))
    head = text.split(begin, 1)[0]
    tail = text.split(end, 1)[1]
    return head + block + tail


def gate_block():
    """The journal gate's output, verbatim, from the committed receipt."""
    if not os.path.exists(RECEIPT):
        raise SystemExit("the journal-gate receipt %s is missing -- refusing to report"
                         % os.path.relpath(RECEIPT, HERE))
    out = open(RECEIPT, encoding="utf-8").read()
    if "GATE:" not in out:
        raise SystemExit("the receipt carries no GATE: verdict line -- it is not the gate's output")
    L = [GATE_BEGIN, "",
         "## The journal reference gate (verbatim output)",
         "",
         "Run from the repository root, on this manuscript, with an interpreter >= 3.12 (the gate's",
         "f-strings carry a backslash):",
         "",
         "```",
         GATE_CMD,
         "```",
         "",
         "Its whole output follows -- the verdict line and every advisory line with it, because",
         "`GATE: PASS` covers only *`entries >= 100`* and *no uncited entries* and says nothing about",
         "the advisories. This run prints **no advisory line**; there is therefore none to resolve.",
         "",
         "```",
         out.rstrip("\n"),
         "```",
         "",
         "This block is a committed receipt (`refgate-journal.txt`) re-rendered here by",
         "`make_reference_check.py`; `reproduce.sh` re-runs the gate and compares its output against the",
         "receipt whenever the journal checkout is present, and reports a named `NOT RUN` when it is not.",
         "",
         GATE_END]
    return "\n".join(L)


def main():
    pool = json.load(open(POOL, encoding="utf-8"))
    text = open(MAN, encoding="utf-8").read()
    if "## References" not in text:
        raise SystemExit("the manuscript carries no '## References' section -- refusing to report")
    refs = text.split("## References", 1)[1]
    rows = []
    for m in re.finditer(r"^\[(\d+)\]\s+(.*)$", refs, re.M):
        n, line = int(m.group(1)), m.group(2)
        ident = re.search(r"https://arxiv\.org/abs/([^\s.]+(?:\.[0-9]+)?)", line)
        if ident:
            key = ident.group(1)
        else:
            doi = re.search(r"https://doi\.org/(\S+)", line)
            if not doi:
                raise SystemExit("entry %d carries no resolvable link -- refusing to report it" % n)
            key = doi.group(1).rstrip(".")
        if key not in pool:
            raise SystemExit("entry %d (%s) is not in the verified pool" % (n, key))
        rows.append((n, key, pool[key]))
    if len(rows) < MIN_REFS:
        raise SystemExit("the manuscript cites %d references; the bar is %d" % (len(rows), MIN_REFS))

    by_source = {}
    for _n, _k, v in rows:
        by_source[v["source"]] = by_source.get(v["source"], 0) + 1

    L = [BEGIN, "",
         "## The cited subset",
         "",
         "The manuscript cites **%d** of the pool's **%d** entries (journal bar %d); the remaining"
         % (len(rows), len(pool), MIN_REFS),
         "%d pool entries are harvested context that no sentence uses, and the build refuses to"
         % (len(pool) - len(rows)),
         "render a citation whose key is absent from the pool -- so a fabricated key cannot enter the",
         "manuscript in the first place. By source: %s."
         % ", ".join("%s %d" % (k, v) for k, v in sorted(by_source.items())),
         "",
         "Every cited key was discovered by `refscan132.py` (never typed from memory) and is verified by",
         "the same live title pass that covers the whole pool; its per-entry verification line is in",
         "`reference-pool.md`, and the machine-readable summary is `citation-verification.json`.",
         "",
         "| # | key | source | verified against | title |",
         "|---|-----|--------|------------------|-------|"]
    for n, key, v in rows:
        method = ("arXiv id_list (title match >= 0.80)" if v["source"] == "arxiv"
                  else "Crossref works/<doi> (title match >= 0.80)")
        L.append("| %d | `%s` | %s | %s | %s |"
                 % (n, key, v["source"], method, v["title"].replace("|", "/")))
    L.append("")
    L.append(END)
    block = "\n".join(L)     # no trailing newline: the separator belongs to the surrounding text

    shipped = open(OUT, encoding="utf-8").read()
    if BEGIN not in shipped or END not in shipped:
        raise SystemExit("reference-check.md does not carry the cited-subset markers")
    # The cited-subset block is the LAST thing in the file: the first draft kept whatever followed END
    # as `tail` and grew the file by one newline per run (rendering was not idempotent, and `--check`
    # could never match).  Nothing follows END; when one day something does, this is the line to change.
    if shipped.split(END, 1)[1].strip():
        raise SystemExit("text follows the cited-subset END marker -- the report's tail is not rendered")
    rendered = replace_block(shipped, GATE_BEGIN, GATE_END, gate_block())
    rendered = replace_block(rendered, BEGIN, END, block)

    if "--check" in sys.argv:
        if rendered != shipped:
            print("REFERENCE-CHECK: MISMATCH -- the shipped report is not what this renders")
            return 1
        print("REFERENCE-CHECK: MATCH -- %d cited entries and the journal-gate receipt "
              "re-rendered byte-identically" % len(rows))
        return 0

    with open(OUT + ".stage", "w", encoding="utf-8") as fh:
        fh.write(rendered)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(OUT + ".stage", OUT)
    print("wrote %s" % os.path.relpath(OUT, HERE))
    print("  cited %d of %d pool entries | sources %s" % (len(rows), len(pool), by_source))
    return 0


if __name__ == "__main__":
    sys.exit(main())
