#!/usr/bin/env python3
"""Render the CITED-SUBSET section of reference-check.md for issue #132.

The report's headline (the pool-level pass) describes the harvested pool of 257 entries, whose
per-entry verification lines are in `reference-pool.md`.  What the manuscript owes on top of that is
the **cited subset**: which of those entries the body actually uses, and confirmation that every one
of them came from the verified pool rather than from memory.

That block is generated here from the built `manuscript.md` and `refs/pool.json` -- never assembled by
hand -- and injected between two markers, so a citation added to the manuscript without a pool entry
cannot appear in the report, and the count cannot drift from the body.  `--check` re-renders into
memory and compares against the shipped file, writing nothing.

Run:  python3 make_reference_check.py            (write reference-check.md, staged then os.replace'd)
      python3 make_reference_check.py --check    (verify the committed report is what this renders)
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "reference-check.md")
MAN = os.path.join(HERE, "manuscript.md")
POOL = os.path.join(HERE, "refs", "pool.json")
BEGIN = "<!-- cited-subset:begin (generated by make_reference_check.py -- do not edit by hand) -->"
END = "<!-- cited-subset:end -->"
MIN_REFS = 100


def main():
    pool = json.load(open(POOL, encoding="utf-8"))
    text = open(MAN, encoding="utf-8").read()
    if "## References" not in text:
        raise SystemExit("the manuscript carries no '## References' section -- refusing to report")
    refs = text.split("## References", 1)[1]
    rows = []
    for m in re.finditer(r"^\[(\d+)\]\s+(.*)$", refs, re.M):
        n, line = int(m.group(1)), m.group(2)
        ident = re.search(r"https://arxiv\.org/abs/([^\s.]+(?:\.[0-9]+)?)", line)
        if ident:
            key = ident.group(1)
        else:
            doi = re.search(r"https://doi\.org/(\S+)", line)
            if not doi:
                raise SystemExit("entry %d carries no resolvable link -- refusing to report it" % n)
            key = doi.group(1).rstrip(".")
        if key not in pool:
            raise SystemExit("entry %d (%s) is not in the verified pool" % (n, key))
        rows.append((n, key, pool[key]))
    if len(rows) < MIN_REFS:
        raise SystemExit("the manuscript cites %d references; the bar is %d" % (len(rows), MIN_REFS))

    by_source = {}
    for _n, _k, v in rows:
        by_source[v["source"]] = by_source.get(v["source"], 0) + 1

    L = [BEGIN, "",
         "## The cited subset",
         "",
         "The manuscript cites **%d** of the pool's **%d** entries (journal bar %d); the remaining"
         % (len(rows), len(pool), MIN_REFS),
         "%d pool entries are harvested context that no sentence uses, and the build refuses to"
         % (len(pool) - len(rows)),
         "render a citation whose key is absent from the pool -- so a fabricated key cannot enter the",
         "manuscript in the first place. By source: %s."
         % ", ".join("%s %d" % (k, v) for k, v in sorted(by_source.items())),
         "",
         "Every cited key was discovered by `refscan132.py` (never typed from memory) and is verified by",
         "the same live title pass that covers the whole pool; its per-entry verification line is in",
         "`reference-pool.md`, and the machine-readable summary is `citation-verification.json`.",
         "",
         "| # | key | source | verified against | title |",
         "|---|-----|--------|------------------|-------|"]
    for n, key, v in rows:
        method = ("arXiv id_list (title match >= 0.80)" if v["source"] == "arxiv"
                  else "Crossref works/<doi> (title match >= 0.80)")
        L.append("| %d | `%s` | %s | %s | %s |"
                 % (n, key, v["source"], method, v["title"].replace("|", "/")))
    L.append("")
    L.append(END)
    block = "\n".join(L) + "\n"

    shipped = open(OUT, encoding="utf-8").read()
    if BEGIN not in shipped or END not in shipped:
        raise SystemExit("reference-check.md does not carry the cited-subset markers")
    head = shipped.split(BEGIN, 1)[0]
    # The block is the LAST thing in the file, so everything from BEGIN to the end is replaced --
    # the first draft kept whatever followed END as `tail` and grew the file by one newline per run
    # (rendering was not idempotent, and `--check` could never match).  Nothing follows END; when
    # one day something does, this is the line that has to change.
    rendered = head + block

    if "--check" in sys.argv:
        if rendered != shipped:
            print("REFERENCE-CHECK: MISMATCH -- the shipped report is not what this renders")
            return 1
        print("REFERENCE-CHECK: MATCH -- %d cited entries re-rendered byte-identically" % len(rows))
        return 0

    with open(OUT + ".stage", "w", encoding="utf-8") as fh:
        fh.write(rendered)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(OUT + ".stage", OUT)
    print("wrote %s" % os.path.relpath(OUT, HERE))
    print("  cited %d of %d pool entries | sources %s" % (len(rows), len(pool), by_source))
    return 0


if __name__ == "__main__":
    sys.exit(main())
