#!/usr/bin/env python3
"""Issue #50 -- the exact command behind every artefact, derived from the artefact itself.

    python3 rebuild_artefacts_v1.py --list                    # the derived command per artefact
    python3 rebuild_artefacts_v1.py --rebuild DIR             # re-run each into DIR and compare
    python3 rebuild_artefacts_v1.py --rebuild DIR --only a,b  # a partial run
    python3 rebuild_artefacts_v1.py --selftest                # liveness: the comparison must be able
                                                              # to report a difference

WHY THIS FILE EXISTS.  Section 6.1 of the manuscript promises that `bash reproduce.sh` rebuilds the
evidence and that the expectation is **byte-identical** output.  Until this file existed the exact
invocation of each sweep lived in the research notes and in the author's memory and **nowhere in the
package** -- so the promise named no command.  One sweep could not have been reconstructed from its own
defaults at all: the committed `boundary_v2_h050.json` was produced with `--extend 3`, and a default run
of the same script reproduces the same schema with a different extent (measured: 163,062 B against
221,526 B, `c_range` [2,5] instead of [1,5]).

WHAT THE FIRST FULL RUN FOUND, and what was done about it.  Twelve artefacts were rebuilt from their
derived commands: **ten reproduced byte-identically on the first attempt**, and two -- the `h = 0.90`
and `h = 1.00` boundary artefacts -- differed in exactly one leaf.  The difference was not a
measurement: every one of the two files' several thousand leaves agreed, and the only differing path was
the top-level `extend` key, which the current `boundary_v2.py` always writes (`"extend": a.extend`) and
which those two committed records did not carry (14 bytes each).  They had been produced by an earlier
revision of the script.  The two records were regenerated by this script's own derived commands, so the
committed bytes are now what the committed code produces; the paper's numbers did not move, because no
measured leaf moved.

THE RULE.  No command is typed here.  Each artefact records the parameters its run varied -- `h`,
`seeds`, `tol`, `extend`, and the seed stream's own first value -- so the command is built by READING
the artefact, and a parameter the artefact does not record raises rather than being guessed.  Two
sweeps take no arguments (`fixedpoint_v1.py`, `external_v1.py`) and are declared `fixed`, which is
itself a claim: that the artefact is a function of the code and its own recorded seeds alone.
"""
import argparse
import hashlib
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, "artefacts")

# artefact -> the script that produced it, and the kind of command it takes
SWEEPS = [
    ("instrument_v0_results.json", "instrument_v0.py", "fixed"),
    ("boundary_v2_h050.json", "boundary_v2.py", "boundary"),
    ("boundary_v2_h090.json", "boundary_v2.py", "boundary"),
    ("boundary_v2_h100.json", "boundary_v2.py", "boundary"),
    ("decompose_v1_h100.json", "decompose_v1.py", "decompose"),
    ("tail_v1_h100.json", "tail_v1.py", "seeded"),
    ("variant_v1.json", "variant_v1.py", "seeded"),
    ("predsplit_v1.json", "predsplit_v1.py", "seeded"),
    ("sideeffect_v1.json", "sideeffect_v1.py", "seeded"),
    ("mechanism_v1.json", "mechanism_v1.py", "seeded"),
    ("fixedpoint_v1.json", "fixedpoint_v1.py", "fixed"),
    ("external_v1.json", "external_v1.py", "fixed"),
]
NAMES = [s[0] for s in SWEEPS]

# The four that finish in seconds, in the order the partial run takes them.  The full set is the
# default: this list exists so that a reader can get a verdict quickly, NOT as the reproduction claim,
# and the README says which is which.
FAST = ("instrument_v0_results.json", "variant_v1.json", "fixedpoint_v1.json", "external_v1.json")


def load(name, art_dir=ART):
    return json.load(io.open(os.path.join(art_dir, name), encoding="utf-8"))


def derive(name, script, kind, dest="<dir>", art_dir=ART):
    """The command for one artefact, read out of the artefact.  Raises if a parameter is missing."""
    out = os.path.join(dest, name)
    if kind == "fixed":
        return [sys.executable, script, "--json", out]
    a = load(name, art_dir)
    argv = [sys.executable, script]
    if kind == "boundary":
        if "seeds" not in a or "tol" not in a:
            raise KeyError("%s does not record its seeds/tol" % name)
        argv += ["--h", "%g" % a["h"], "--seeds", str(len(a["seeds"])), "--tol", "%g" % a["tol"]]
        # `extend` is written only when the run used it; absent means the script's own default (0)
        if a.get("extend"):
            argv += ["--extend", str(a["extend"])]
    elif kind == "decompose":
        if "seeds" not in a or "tol" not in a:
            raise KeyError("%s does not record its seeds/tol" % name)
        argv += ["--h", "%g" % a["h"], "--seeds", str(len(a["seeds"])), "--tol", "%g" % a["tol"]]
    elif kind == "seeded":
        if "seeds" not in a:
            raise KeyError("%s does not record its seeds" % name)
        seeds = a["seeds"]
        argv += ["--seeds", str(len(seeds)), "--seed0", str(seeds[0])]
        if "h" in a:
            argv += ["--h", "%g" % a["h"]]
    else:
        raise ValueError(kind)
    argv += ["--json", out]
    return argv


def sha(path):
    with io.open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def compare(a, b):
    """The decision, in one place, so the liveness control can call the same function the run calls:
    byte-identical or not -- never "close enough" for a deterministic instrument."""
    if not os.path.exists(b):
        return False
    return sha(a) == sha(b)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--rebuild", metavar="DIR")
    ap.add_argument("--only", default=None, help="comma-separated artefact names, for a partial run")
    a = ap.parse_args()

    only = set(a.only.split(",")) if a.only else None
    rows = [r for r in SWEEPS if only is None or r[0] in only]
    if a.only and not rows:
        print("no artefact named by --only %s" % a.only)
        return 2

    if a.list:
        print("artefact -> the command derived from the artefact's own recorded parameters")
        for name, script, kind in rows:
            # the interpreter is printed as `python3` rather than as this machine's executable: the
            # path is a coordinate of the caller, and a command list a reader cannot re-type is not a
            # command list.  The interpreter actually used is declared on reproduce.sh's first line.
            argv = [os.path.basename(x) if os.sep in x else x for x in derive(name, script, kind)]
            argv[0] = 'python3' 
            print("  %-28s %s" % (name, " ".join(argv)))
        return 0

    if not a.rebuild:
        print("nothing to do: pass --list or --rebuild DIR")
        return 2

    dest = os.path.abspath(a.rebuild)
    if not os.path.isdir(dest):
        os.makedirs(dest)
    bad = 0
    print("rebuilding %d artefact(s) into %s" % (len(rows), os.path.relpath(dest, HERE)))
    for name, script, kind in rows:
        argv = derive(name, script, kind, dest=dest)
        committed = os.path.join(ART, name)
        r = subprocess.run(argv, cwd=ART, capture_output=True, text=True)
        built = os.path.join(dest, name)
        if r.returncode != 0:
            print("  FAIL %-28s %s exited %d: %s" % (name, script, r.returncode,
                                                     (r.stderr or r.stdout).strip().splitlines()[-1][:90]))
            bad += 1
            continue
        same = compare(committed, built)
        print("  %-4s %-28s %8d B  sha %s%s" % ("ok" if same else "DIFF", name, os.path.getsize(built),
                                                sha(built)[:16],
                                                "" if same else " (committed %s)" % sha(committed)[:16]))
        sys.stdout.flush()
        if not same:
            bad += 1
    print("REBUILD: %d of %d byte-identical, %d differing" % (len(rows) - bad, len(rows), bad))
    return 0 if bad == 0 else 1


# ------------------------------------------------------------------------------------------- selftest
def selftest():
    """Two sides of the comparison the verdict is read off: a rebuilt file must be reported
    byte-identical, and a file whose bytes have moved must be reported different.  A comparison that
    can only say "same" is a comparison that has never been tested."""
    bad = 0
    tmp = tempfile.mkdtemp(prefix="issue50-rebuild-")
    try:
        out = os.path.join(tmp, "out")
        os.makedirs(out)
        name = FAST[0]                                   # the cheapest sweep: seconds, not minutes
        script = dict((s[0], s[1]) for s in SWEEPS)[name]
        argv = derive(name, script, "fixed", dest=out)
        r = subprocess.run(argv, cwd=ART, capture_output=True, text=True)
        if r.returncode != 0 or not os.path.exists(os.path.join(out, name)):
            print("  base  %s: the sweep itself did not run (exit %d) -- control void"
                  % (name, r.returncode))
            return 1
        same = compare(os.path.join(ART, name), os.path.join(out, name))
        print("  base  %-28s rebuilt from the derived command: %s"
              % (name, "byte-identical" if same else "DIFFERS from the committed artefact"))
        if not same:
            bad += 1
        # ... and the other side: move one leaf in a throwaway copy of the committed file
        moved = os.path.join(tmp, "moved.json")
        doc = load(name)
        doc["selftest_plant"] = {"moved": True}
        io.open(moved, "w", encoding="utf-8").write(json.dumps(doc, indent=1, sort_keys=True))
        diff = not compare(moved, os.path.join(out, name))
        print("  plant %-28s one leaf added to a copy: %s"
              % (name, "reported as DIFF" if diff else "REPORTED AS IDENTICAL (control void)"))
        if not diff:
            bad += 1
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print("REBUILD SELFTEST: 2 case(s), %d not firing" % bad)
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(selftest() if "--selftest" in sys.argv else main())
