#!/usr/bin/env python3
"""Render issue #50's `## References` section in the JOURNAL's house style.

Taken from `papers/issue-38/refs_render.py` (the newest accepted copy of this form, which is
where the two folds below were learned and where the reads that watch them live).  What is
this package's own: the input files, and the fact that this file owns the SECTION while
`assemble.py` owns the BODY before it.  Two writers, two objects, and each `--check` names the
object it read -- the arrangement the journal's references corrections arrived at the hard way.

ENTRY STYLE -- the form `README.md` (the journal's) -> *Presentation requirements* -> *Formal
References section* states:

    [n] Authors (Year). Title. Venue or identifier. <resolvable URL>
        Difference: <the one-line stated difference that closes the entry>

  * Authors are `Family, I.`, joined with `; `; four or more are abbreviated to the first three
    followed by `et al.` (one period, written here, so a doubled period cannot be emitted).
  * The year is in **parentheses**, after the author block.
  * An entry whose record carries no author is printed with no author block: the record is not
    padded with an invented author (`refs_build_display.py` records which entries these are).
  * The title is the record's own, in title case for an ALL-CAPS record; a title the record
    carries polluted is printed from a declaration that is verified as a prefix of the record.
  * The link is a **resolvable URL** -- `https://doi.org/...` or `https://arxiv.org/abs/...`.
  * ENTRIES ARE SEPARATED BY A BLANK LINE: without it consecutive entries are ONE paragraph to
    every CommonMark renderer, so the boundaries vanish (measured in this journal: 103 entries
    read as 1 paragraph before the fix).  The acceptance read is `refgate.py`'s
    `block form: N entries, 0 of them not separated`.

Author components and record text are folded here (ALL-CAPS components, XML character
references); both are read back off the rendered section by `--check`, because a section
regenerated by a renderer that lost a fold agrees with that renderer.

Usage:
    python3 refs_render.py            rewrite the section in manuscript.md (appending if absent)
    python3 refs_render.py --check    exit non-zero if the committed section differs (no write)
"""
import html
import io
import json
import os
import re
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
MS = os.path.join(HERE, "manuscript.md")
MAX_AUTHORS = 3          # four or more authors -> first three + `et al.`
WIDTH = 100
# The heading this file EMITS is the unnumbered `## References` the house style names.  The numbered
# form is still accepted when reading, because the renderer rewrites a file whose heading it must
# first find, and a rewrite that cannot locate its own section would append a second one.
HDR = re.compile(r'^##\s*(?:\d+\.\s*)?References\s*$')

# Words that stay lowercase inside a title-cased phrase (never the first word).
SMALL = ("Of", "The", "And", "For", "In", "On", "To", "With", "A", "An")


def load():
    refs = json.load(io.open(os.path.join(HERE, "references.json"), encoding="utf-8"))["entries"]
    disp = json.load(io.open(os.path.join(HERE, "refs_display.json"), encoding="utf-8"))
    return refs, disp


def title_case(t):
    """Fold an ALL-CAPS record title to title case; leave a mixed-case title alone.

    The house style asks for the title in title case, and 2 of the 125 records return it in capitals
    (Crossref keeps the publisher's own casing).  A record whose letters are ALL upper-case is folded;
    anything else is printed as the record states it, because re-casing a title the publisher wrote in
    mixed case would be an edit to the record rather than a rendering of it.
    """
    letters = [c for c in t if c.isalpha()]
    if not letters or not all(c.isupper() for c in letters):
        return t
    out = t.title()
    out = re.sub(r"\b(%s)\b" % "|".join(SMALL), lambda m: m.group(0).lower(), out)
    return out[0].upper() + out[1:] if out else out


def author_case(a):
    """Fold an ALL-CAPS record author component the way this file folds an ALL-CAPS title.

    Deliberately NOT `title_case`: that function's small-word rule is written for title phrases, and
    over an author component it lowercases an initial (`SMITH, A. B.` -> `Smith, a. B.`, where
    `.title()` alone gives `Smith, A. B.`).  A component whose letters are all upper-case is folded;
    anything else is printed as the record states it, because re-casing a name the registry wrote in
    mixed case would be an edit to the record rather than a rendering of it.
    """
    letters = [c for c in a if c.isalpha()]
    if not letters or not all(c.isupper() for c in letters):
        return a
    return a.title()


def record_text(s):
    """Decode the XML/HTML character references the registries ship inside their metadata.

    The data layer is the record AS READ, so the escape stays there; the page wants the character.
    Decoding repeats, because a record can escape an escape: measured at R380, one title reads
    `Amdahl&amp;#x0027;s law`, which needs TWO passes to become `Amdahl's law` -- a single pass leaves
    `&#x0027;` in the page, which is what this package's first render did.

    The loop is bounded and the count of passes is available to `--check`, so a record that never
    settles is a reported fact rather than a hang.
    """
    if not s:
        return s
    for _ in range(4):
        t = html.unescape(s)
        if t == s:
            break
        s = t
    return s


def author_string(authors):
    """`Family, I.`, joined with `; `; four or more collapsed to the first three and `et al.`"""
    if not authors:
        return ""
    names = [author_case(record_text(a)) for a in authors]
    if len(names) >= 4:
        return "; ".join(names[:MAX_AUTHORS]) + "; et al."
    return "; ".join(names)


def caps_author_components(sec):
    """The ALL-CAPS author components of a RENDERED section, read from the text a reader sees.

    An entry's author block runs from `[n] ` to its year in parentheses -- an author component carries
    no parentheses -- and components are separated by `; `, which is also why `et al.` is a component of
    its own and is correctly not in capitals.  Whitespace is collapsed first, so a block the wrapper
    broke across lines is read as the one block it is.
    """
    out = []
    for blk in re.split(r"(?m)^(?=\[\d+\] )", sec.strip("\n")):
        m = re.match(r"^\[(\d+)\] (.*?) \((?:19|20)\d\d\)\.", re.sub(r"\s+", " ", blk).strip())
        if not m:
            continue
        # split on `; ` and not on `;`: a character reference ENDS in a semicolon (`&#39;`), and
        # splitting on the bare semicolon cuts a component in half -- which is how this read first
        # reported `[95] O&#39` as an ALL-CAPS component, a false positive.
        for comp in m.group(2).split("; "):
            comp = comp.strip()
            letters = [c for c in comp if c.isalpha()]
            if letters and all(c.isupper() for c in letters):
                out.append((m.group(1), comp))
    return out


def decode_passes(s):
    """How many decoding passes a record value needs before it settles (bounded)."""
    n = 0
    while n < 4 and s:
        t = html.unescape(s)
        if t == s:
            break
        s, n = t, n + 1
    return n


ENT = re.compile(r"&#?[0-9A-Za-z]+;")


def escaped_entities(text):
    """The character references left in TEXT -- the object every text reader sees."""
    return ENT.findall(text or "")


def source_entities(disp, refs):
    """The escapes the RECORDS state in the fields this renderer prints -- the liveness fact."""
    out = []
    for k, rec in disp.items():
        for a in (rec.get("authors") or []):
            if escaped_entities(a):
                out.append((k, a))
        if escaped_entities(rec.get("venue") or ""):
            out.append((k, rec["venue"]))
    for e in refs:
        for field in ("title", "venue"):
            if escaped_entities(e.get(field) or ""):
                out.append((str(e["key"]), e[field]))
    out.sort(key=lambda kv: int(kv[0]))
    return out


def source_caps(disp):
    """The author components the RECORD states in capitals -- the liveness precondition of that read.

    With none of these, `caps_author_components` returns 0 over the section whatever the renderer did,
    so the acceptance read would be satisfied by there being nothing to fold.
    """
    out = []
    for k, rec in disp.items():
        for a in (rec.get("authors") or []):
            letters = [c for c in a if c.isalpha()]
            if letters and all(c.isupper() for c in letters):
                out.append((k, a))
    out.sort(key=lambda kv: int(kv[0]))
    return out


def entry_line(e, d):
    au = author_string(d.get("authors") or [])
    year = d.get("year") or ""
    if au:
        head = au
    else:
        # The record itself carries no author field (dois to edited books, reference entries, one
        # proceedings chapter and one journal article whose record omits it). The entry says so
        # rather than inventing an author; `reference-check.md` names the four.
        head = "Author not stated in the record"
    head += (" (%s)." % year) if year else "."
    venue = d.get("venue") or ""
    bits = [("[%d] " % e["key"]) + head, title_case(record_text(e["title"])) + "."]
    if venue:
        bits.append(venue + ".")
    bits.append(e["url"])
    first = " ".join(bits)
    diff = "Difference: " + (e.get("difference") or "").strip()
    out = textwrap.wrap(first, width=WIDTH, subsequent_indent="    ",
                        break_long_words=False, break_on_hyphens=False)
    out += textwrap.wrap(diff, width=WIDTH, initial_indent="    ", subsequent_indent="    ",
                         break_long_words=False, break_on_hyphens=False)
    return "\n".join(out)


def render():
    refs, disp = load()
    body = ["## References", ""]
    for i, e in enumerate(refs):
        if i:
            body.append("")          # the blank line that makes each entry its own paragraph
        body.append(entry_line(e, disp[str(e["key"])]))
    return "\n".join(body) + "\n"


def main():
    check = "--check" in sys.argv
    ms = io.open(MS, encoding="utf-8").read()
    lines = ms.split("\n")
    starts = [i for i, l in enumerate(lines) if HDR.match(l)]
    if len(starts) > 1:
        print("ABORT: expected at most one '## ... References' heading, found %d" % len(starts))
        return 1
    if not starts:
        if check:
            print("references section: ABSENT from manuscript.md, so there is no rendered section "
                  "to compare with (the body is owned by assemble.py and this file owns the section)")
            return 1
        head_at = len(lines)
    else:
        head_at = starts[0]
    old_sec = "\n".join(lines[head_at:])
    if check:
        sec = render()
        same = old_sec.rstrip("\n") == sec.rstrip("\n")
        print("section (manuscript.md from the '## References' heading): matches the renderer: %s" % same)
        refs, disp = load()
        ents = len(re.findall(r"(?m)^\[\d+\] ", sec))
        blanks = sum(1 for l in sec.split("\n") if not l.strip())
        print("  %d entries, %d blank line(s) in the section, heading %r"
              % (ents, blanks, sec.split("\n")[0]))
        # The author component's case is read on the SECTION, the object the reader's page comes from,
        # and not on the renderer's own behaviour: a section regenerated by a renderer that lost the
        # fold agrees with that renderer, so the comparison above cannot see it and this read can.
        caps = caps_author_components(sec)
        src = source_caps(disp)
        print("  author case: %d ALL-CAPS author component(s) over %d entries%s"
              % (len(caps), ents, "" if not caps else " -- " + "; ".join("[%s] %s" % c for c in caps)))
        print("  liveness: %d component(s) in %d record(s) are stated in capitals by the record read"
              % (len(src), len(set(k for k, _ in src))))
        esc = escaped_entities(sec)
        srce = source_entities(disp, refs)
        deepest = max([0] + [decode_passes(v) for _, v in srce])
        print("  record text: the deepest record escape needs %d decoding pass(es); the section must carry 0"
              % deepest)
        print("  record text: %d escaped character reference(s) over %d entries%s"
              % (len(esc), ents, "" if not esc else " -- " + ", ".join(sorted(set(esc)))))
        print("  liveness: %d escaped reference(s) in %d record(s) are stated by the record read"
              % (len(srce), len(set(k for k, _ in srce))))
        # the two liveness lines are FACTS, not failures: an artefact in which nothing needed folding or
        # decoding is correct.  What must fail when a rule has nothing to exercise is the round's
        # control, which verify_correction_r3.py derives and refuses to skip.
        return 0 if (same and not caps and not esc) else 1
    new_ms = "\n".join(lines[:head_at]).rstrip("\n") + "\n\n" + render()
    io.open(MS, "w", encoding="utf-8").write(new_ms)
    ents = sum(1 for l in render().split("\n") if re.match(r'^\[\d+\]', l))
    print("rendered %d entries into %s" % (ents, os.path.basename(MS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
