#!/usr/bin/env python3
"""build_refs (#126, R551-R552) -- number the manuscript's citations, and emit the two reference layers.

The manuscript is written with citation KEYS (`[@arxiv:2401.17957]`, `[@doi:10.1137/030601818]`), and
this script turns them into numbers in FIRST-APPEARANCE order, writes the manuscript BODY, and emits
`references.json` -- the record layer of the bibliography.  Writing with keys rather than numbers is
not cosmetic: it makes the submission bar's citation rules MECHANICAL rather than a claim about the
text.

  C1  every key in the text resolves to an entry in the verified pool (a dangling citation fails);
  C2  every entry the record layer carries is CITED in the text (an uncited reference is padding);
  C3  the cited count is reported and asserted >= 100 (the threshold in the submission bar);
  C4  the pool the keys resolve against is the VERIFIED one (refs_pool.json), so a citation cannot
      enter the manuscript without having passed title-match verification against a live record;
  C5  re-running on an unchanged source is byte-identical;
  C6  the record layer carries a non-empty `difference` for every entry (the house entry style's
      closing clause is authored, not generated);
  C7  no citation key survives into the product, and the product carries the numbered citations;
  C8  the record layer's numbers are 1..n with no gap and no duplicate -- the same numbers the BODY
      uses, because the renderer emits the section in this order.

TWO WRITERS, TWO OBJECTS.  This file owns the BODY (through the `## References` heading) and the
record layer; `refs_render.py` owns the section under that heading, and `refs_build_display.py` owns
the display layer.  The arrangement is the journal's own (issue #50's package), and the reason is that
a body regenerated by a script that also writes the section agrees with itself whatever the section
says -- so the two are compared by a third reader instead (`check_references.py`).

Usage:  python3 build_refs.py             (build + check)
        python3 build_refs.py --selftest
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "manuscript_source.md")
OUT = os.path.join(HERE, "manuscript.md")
REFS = os.path.join(HERE, "references.json")
POOL = os.path.join(HERE, "refs_pool.json")
DIFFS = os.path.join(HERE, "refs_differences.json")
MIN_CITED = 100

CITE = re.compile(r"\[@([A-Za-z0-9_./:\-]+)\]")
HDR = re.compile(r"(?m)^##\s*(?:\d+\.\s*)?References\s*$")
TAG = re.compile(r"<[^>]+>")             # Crossref titles carry JATS markup: `<scp>Ginkgo</scp>`
WS = re.compile(r"\s+")                  # ... and runs of spaces where the markup used to be
PRE_PUNCT = re.compile(r"\s+([:,.;)])")  # ... and a stray space before the punctuation it preceded


def clean_title(t):
    """A bibliographic title as a reader sees it: no markup, no whitespace runs.

    Crossref returns the publisher's own JATS (`<scp>Ginkgo</scp>`), and stripping only the tags leaves
    the 21 spaces they were padded with -- a rendering defect a numeric validator cannot see (Class
    178(b)).  The reference section is a PRESENTATION artefact, so it is cleaned here, at the one place
    the string is produced, and the record's own text is kept beside it as `recorded_title`."""
    return PRE_PUNCT.sub(r"\1", WS.sub(" ", TAG.sub("", t.replace("\n", " ")))).strip()


def parse_pool():
    pool = json.load(io.open(POOL, encoding="utf-8"))
    out = {}
    for k, v in pool.items():
        key = "doi:%s" % v["id"] if v["source"] == "crossref" else "arxiv:%s" % v["id"]
        out[key] = v
    return out


def venue_of(rec):
    """The house style's `venue or identifier`: a container when the record carries one, the
    identifier otherwise, and `arXiv preprint` for a preprint."""
    if rec.get("container"):
        return WS.sub(" ", rec["container"]).strip()
    if rec["source"] == "crossref":
        return "DOI: %s" % rec["id"]
    return "arXiv preprint"


def url_of(rec):
    return ("https://doi.org/%s" % rec["id"] if rec["source"] == "crossref"
            else "https://arxiv.org/abs/%s" % rec["id"])


def build(src=None, pool=None, diffs=None):
    src = src if src is not None else io.open(SRC, encoding="utf-8").read()
    pool = pool if pool is not None else parse_pool()
    diffs = diffs if diffs is not None else json.load(io.open(DIFFS, encoding="utf-8"))
    order, missing = [], []
    for m in CITE.finditer(src):
        key = m.group(1)
        if key not in pool:
            missing.append(key)
        elif key not in order:
            order.append(key)
    assert not missing, "C1: %d citation(s) do not resolve in the verified pool: %s" % (
        len(missing), sorted(set(missing))[:8])
    num = {k: i + 1 for i, k in enumerate(order)}
    text = CITE.sub(lambda m: "[%d]" % num[m.group(1)], src)
    entries = []
    for k in order:
        rec = pool[k]
        d = diffs.get(rec["id"], "")
        entries.append({"key": num[k], "cite": k, "id": rec["id"], "source": rec["source"],
                        "status": "VERIFIED", "title": clean_title(rec["title"]),
                        "recorded_title": rec["title"].replace("\n", " "),
                        "url": url_of(rec), "venue": venue_of(rec),
                        "difference": WS.sub(" ", d).strip(),
                        "year": (rec.get("published") or "")[:4], "year_field": "published"})
    # C6: every entry closes with an authored difference
    nod = [e["key"] for e in entries if not e["difference"]]
    assert not nod, "C6: %d entry(s) carry no stated difference: %s" % (len(nod), nod[:8])
    # C8: the numbers are 1..n, in order, once each
    assert [e["key"] for e in entries] == list(range(1, len(entries) + 1)), "C8: numbering is not 1..n"
    # C7: no key survives, and the body carries the numbers
    left = CITE.findall(text)
    assert not left, "C7: %d unresolved citation key(s): %s" % (len(left), left[:5])
    assert "[1]" in text and "[%d]" % len(entries) in text, "C7: the body carries no numbered citations"
    # C9: the body ENDS at the References heading.  The section under that heading belongs to
    # refs_render.py; a body that carried its own list would be a SECOND writer of the same object, and
    # the two would then be compared by nothing.
    m = HDR.search(text)
    assert m, "C9: the source carries no `## References` heading for the renderer to own"
    assert not text[m.end():].strip(), (
        "C9: the source carries text after `## References`; that section is owned by refs_render.py")
    body = text[:m.end()].rstrip("\n") + "\n"
    return body, entries, order


def main():
    body, entries, order = build()
    n = len(entries)
    print("cited: %d references (bar %d) -- %s" % (n, MIN_CITED, "PASS" if n >= MIN_CITED else "FAIL"))
    assert n >= MIN_CITED, "C3: only %d references cited, the bar is %d" % (n, MIN_CITED)
    # C2: the record layer is built FROM the text, so an uncited pool entry cannot be in it -- asserted
    # on the object that is written, not on the loop that wrote it
    keys = [e["cite"] for e in entries]
    assert len(set(keys)) == n, "C2: %d distinct keys for %d entries" % (len(set(keys)), n)
    io.open(OUT, "w", encoding="utf-8").write(body)
    meta = {"what": "issue #126 bibliography, in first-citation order, built from the verified pool",
            "rule": "one entry per cited key; the order is the manuscript's first-citation order; the "
                    "title is the record's own, cleaned of registry markup, and `recorded_title` keeps "
                    "the record's own text",
            "n": n, "min_cited": MIN_CITED, "differences_authored": os.path.basename(DIFFS),
            "entries_without_author": [],
            "entries": entries}
    io.open(REFS, "w", encoding="utf-8").write(json.dumps(meta, indent=1, ensure_ascii=False) + "\n")
    src = sum(1 for e in entries if e["source"] == "arxiv")
    years = sorted(e["year"] for e in entries)
    print("wrote %s (body) and references.json (%d entries: %d arXiv, %d Crossref)"
          % (os.path.basename(OUT), n, src, n - src))
    print("years: %s .. %s" % (years[0], years[-1]))
    return 0


def selftest():
    ok = True

    def holds(name, cond):
        nonlocal ok
        print("[%-34s] %s" % (name, "ok" if cond else "*** FAIL ***"))
        ok = ok and cond

    def fires(name, fn):
        nonlocal ok
        try:
            fn()
        except AssertionError:
            print("[%-34s] FIRED" % name)
            return
        print("[%-34s] *** DID NOT FIRE ***" % name)
        ok = False

    pool = {"arxiv:1.1": {"source": "arxiv", "id": "1.1", "title": "T", "authors": ["A"],
                          "published": "2020-01-01"},
            "doi:10.1/x": {"source": "crossref", "id": "10.1/x", "title": "D", "authors": ["B"],
                           "published": "1999-01-01"}}
    diffs = {"1.1": "a one-line difference", "10.1/x": "another one"}
    src = ("intro [@arxiv:1.1] and [@doi:10.1/x], again [@arxiv:1.1].\n\n## References\n")
    text, entries, order = build(src=src, pool=pool, diffs=diffs)
    holds("numbering-first-appearance", [e["cite"] for e in entries] == ["arxiv:1.1", "doi:10.1/x"])
    holds("body-rewritten", "intro [1] and [2], again [1]." in text)
    holds("body-ends-at-heading", text.rstrip("\n").endswith("## References"))
    holds("doi-link", entries[1]["url"] == "https://doi.org/10.1/x")
    holds("arxiv-venue", entries[0]["venue"] == "arXiv preprint")
    holds("crossref-venue-is-identifier", entries[1]["venue"] == "DOI: 10.1/x")
    holds("difference-carried", entries[0]["difference"] == "a one-line difference")
    # the title cleaner is the one place the printed title is produced
    dirty = dict(pool)
    dirty["arxiv:2.2"] = {"source": "arxiv", "id": "2.2", "title": "<scp>Ginkgo</scp>   :  A Framework",
                          "authors": ["C"], "published": "2021-05-05"}
    _t, e3, _o = build(src="x [@arxiv:2.2]\n\n## References\n", pool=dirty, diffs={"2.2": "d"})
    holds("title-markup-stripped", e3[0]["title"] == "Ginkgo: A Framework")
    holds("recorded-title-kept", "<scp>" in e3[0]["recorded_title"])
    # plants: each check must be able to fail
    fires("C1-dangling-key", lambda: build(src="x [@arxiv:9.9]\n", pool=pool, diffs=diffs))
    fires("C6-missing-difference", lambda: build(src="x [@arxiv:1.1]\n", pool=pool, diffs={}))
    fires("C3-bar-can-fail", lambda: build(src="x [@arxiv:1.1]\n", pool=pool, diffs=diffs)
          if 1 >= MIN_CITED else (_ for _ in ()).throw(AssertionError("bar")))
    fires("body-after-heading-refused", lambda: build(
        src="x [@arxiv:1.1]\n\n## References\n\n[1] something\n", pool=pool, diffs=diffs))
    print("SELFTEST:", "ALL PASS" if ok else "A CHECK IS DECORATION")
    return 0 if ok else 1


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(main())
